language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.0
      env: COVERGAE=1 DEFAULT=0

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0
    - php: 7.0
      env: COVERAGE=1 DEFAULT=0

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - phpenv rehash

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2; fi"
  - sh -c "if [ '$COVERAGE' = '1' ]; then vendor/bin/phpunit --coverage-text; fi"